// <auto-generated />
using System;
using API.Documents.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Documents.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230919011609_SetDocumentsLines2")]
    partial class SetDocumentsLines2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Documents.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("do_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("co_id")
                        .HasColumnOrder(2);

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("do_contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("do_created_at")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("do_date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("do_deleted_at")
                        .HasColumnOrder(12);

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("do_document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("do_document_type");

                    b.Property<string>("HashCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("co_hash_id")
                        .HasColumnOrder(3);

                    b.Property<string>("HashCreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_hash_created_at")
                        .HasColumnOrder(7);

                    b.Property<string>("HashDeletedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_hash_deleted_at")
                        .HasColumnOrder(13);

                    b.Property<string>("HashDocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_hash_document_number");

                    b.Property<string>("HashId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_hash_id")
                        .HasColumnOrder(1);

                    b.Property<string>("HashModifiedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_hash_modified_at")
                        .HasColumnOrder(9);

                    b.Property<string>("HashUsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_modified_id")
                        .HasColumnOrder(11);

                    b.Property<string>("HashUserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_creater_id")
                        .HasColumnOrder(5);

                    b.Property<string>("HashUserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_deleter_id")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("do_is_deleted")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("do_modified_at")
                        .HasColumnOrder(8);

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("do_shipping_address_id");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("do_shipping_date");

                    b.Property<int>("ThirdAccountId")
                        .HasColumnType("int")
                        .HasColumnName("do_third_account_id");

                    b.Property<string>("UsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_modified_id")
                        .HasColumnOrder(10);

                    b.Property<string>("UserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_creater_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_deleter_id")
                        .HasColumnOrder(15);

                    b.Property<int?>("WarehouseDestinationId")
                        .HasColumnType("int")
                        .HasColumnName("do_warehouse_destination_id");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("do_warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DocumentNumber", "DocumentType")
                        .IsUnique();

                    b.ToTable("do_document");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dl_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("co_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("dl_created_at")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("dl_deleted_at")
                        .HasColumnOrder(12);

                    b.Property<string>("HashCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("co_hash_id")
                        .HasColumnOrder(3);

                    b.Property<string>("HashCreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dl_hash_created_at")
                        .HasColumnOrder(7);

                    b.Property<string>("HashDeletedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dl_hash_deleted_at")
                        .HasColumnOrder(13);

                    b.Property<string>("HashId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dl_hash_id")
                        .HasColumnOrder(1);

                    b.Property<string>("HashModifiedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dl_hash_modified_at")
                        .HasColumnOrder(9);

                    b.Property<string>("HashUsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_modified_id")
                        .HasColumnOrder(11);

                    b.Property<string>("HashUserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_creater_id")
                        .HasColumnOrder(5);

                    b.Property<string>("HashUserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_deleter_id")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsBundle")
                        .HasColumnType("bit")
                        .HasColumnName("dl_is_bundle");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("dl_is_deleted")
                        .HasColumnOrder(14);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dl_label");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("dl_modified_at")
                        .HasColumnOrder(8);

                    b.Property<string>("UsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_modified_id")
                        .HasColumnOrder(10);

                    b.Property<string>("UserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_creater_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_deleter_id")
                        .HasColumnOrder(15);

                    b.Property<long>("do_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("do_id");

                    b.ToTable("dl_document_line");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineBundle", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("lb_id")
                        .HasColumnOrder(0);

                    b.Property<int>("BundleId")
                        .HasColumnType("int")
                        .HasColumnName("lb_bundle_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("co_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lb_created_at")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lb_deleted_at")
                        .HasColumnOrder(12);

                    b.Property<double>("Discount")
                        .HasColumnType("float")
                        .HasColumnName("lb_discount");

                    b.Property<string>("HashCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("co_hash_id")
                        .HasColumnOrder(3);

                    b.Property<string>("HashCreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lb_hash_created_at")
                        .HasColumnOrder(7);

                    b.Property<string>("HashDeletedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lb_hash_deleted_at")
                        .HasColumnOrder(13);

                    b.Property<string>("HashId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lb_hash_id")
                        .HasColumnOrder(1);

                    b.Property<string>("HashModifiedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lb_hash_modified_at")
                        .HasColumnOrder(9);

                    b.Property<string>("HashUsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_modified_id")
                        .HasColumnOrder(11);

                    b.Property<string>("HashUserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_creater_id")
                        .HasColumnOrder(5);

                    b.Property<string>("HashUserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_deleter_id")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("lb_is_deleted")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lb_modified_at")
                        .HasColumnOrder(8);

                    b.Property<double>("NetPrice")
                        .HasColumnType("float")
                        .HasColumnName("lb_net_price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("lb_quantity");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("lb_total_price");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("lb_unit_price");

                    b.Property<string>("UsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_modified_id")
                        .HasColumnOrder(10);

                    b.Property<string>("UserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_creater_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_deleter_id")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.ToTable("lb_document_line_bundle");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineBundleElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("le_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BundleElementId")
                        .HasColumnType("int")
                        .HasColumnName("le_bundle_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("co_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("le_created_at")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("le_deleted_at")
                        .HasColumnOrder(12);

                    b.Property<string>("HashCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("co_hash_id")
                        .HasColumnOrder(3);

                    b.Property<string>("HashCreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("le_hash_created_at")
                        .HasColumnOrder(7);

                    b.Property<string>("HashDeletedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("le_hash_deleted_at")
                        .HasColumnOrder(13);

                    b.Property<string>("HashId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("le_hash_id")
                        .HasColumnOrder(1);

                    b.Property<string>("HashModifiedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("le_hash_modified_at")
                        .HasColumnOrder(9);

                    b.Property<string>("HashUsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_modified_id")
                        .HasColumnOrder(11);

                    b.Property<string>("HashUserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_creater_id")
                        .HasColumnOrder(5);

                    b.Property<string>("HashUserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_deleter_id")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("le_is_deleted")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("le_modified_at")
                        .HasColumnOrder(8);

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("le_total_price");

                    b.Property<string>("UsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_modified_id")
                        .HasColumnOrder(10);

                    b.Property<string>("UserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_creater_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_deleter_id")
                        .HasColumnOrder(15);

                    b.Property<long>("lb_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("lb_id");

                    b.ToTable("le_document_line_bundle_element");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineVariant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("lv_id")
                        .HasColumnOrder(0);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("co_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lv_created_at")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lv_deleted_at")
                        .HasColumnOrder(12);

                    b.Property<double>("Discount")
                        .HasColumnType("float")
                        .HasColumnName("lv_discount");

                    b.Property<string>("HashCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("co_hash_id")
                        .HasColumnOrder(3);

                    b.Property<string>("HashCreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lv_hash_created_at")
                        .HasColumnOrder(7);

                    b.Property<string>("HashDeletedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lv_hash_deleted_at")
                        .HasColumnOrder(13);

                    b.Property<string>("HashId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lv_hash_id")
                        .HasColumnOrder(1);

                    b.Property<string>("HashModifiedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lv_hash_modified_at")
                        .HasColumnOrder(9);

                    b.Property<string>("HashUsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_modified_id")
                        .HasColumnOrder(11);

                    b.Property<string>("HashUserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_creater_id")
                        .HasColumnOrder(5);

                    b.Property<string>("HashUserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_hash_deleter_id")
                        .HasColumnOrder(16);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("lv_is_deleted")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lv_modified_at")
                        .HasColumnOrder(8);

                    b.Property<double>("NetPrice")
                        .HasColumnType("float")
                        .HasColumnName("lv_net_price");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("lv_product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("lv_quantity");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("lv_total_price");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("lv_unit_price");

                    b.Property<string>("UsedIdModifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_modified_id")
                        .HasColumnOrder(10);

                    b.Property<string>("UserIdCreater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_creater_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserIdDeleter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("us_deleter_id")
                        .HasColumnOrder(15);

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("lv_variant_id");

                    b.HasKey("Id");

                    b.ToTable("lv_document_line_variant");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLine", b =>
                {
                    b.HasOne("API.Documents.Models.Document", "Document")
                        .WithMany("Lines")
                        .HasForeignKey("do_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineBundle", b =>
                {
                    b.HasOne("API.Documents.Models.DocumentLine", "DocumentLine")
                        .WithOne("DocumentLineBundle")
                        .HasForeignKey("API.Documents.Models.DocumentLineBundle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentLine");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineBundleElement", b =>
                {
                    b.HasOne("API.Documents.Models.DocumentLineBundle", "DocumentLineBundle")
                        .WithMany("BundleElements")
                        .HasForeignKey("lb_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentLineBundle");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineVariant", b =>
                {
                    b.HasOne("API.Documents.Models.DocumentLine", "DocumentLine")
                        .WithOne("DocumentLineVariant")
                        .HasForeignKey("API.Documents.Models.DocumentLineVariant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentLine");
                });

            modelBuilder.Entity("API.Documents.Models.Document", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLine", b =>
                {
                    b.Navigation("DocumentLineBundle");

                    b.Navigation("DocumentLineVariant");
                });

            modelBuilder.Entity("API.Documents.Models.DocumentLineBundle", b =>
                {
                    b.Navigation("BundleElements");
                });
#pragma warning restore 612, 618
        }
    }
}
