version: "3.9"

networks:
    backend:
    products:

services:
    db-products:
        container_name: mssql-products
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1445:1433
        environment:
            MSSQL_SA_PASSWORD: Pass@word
            ACCEPT_EULA: Y
        networks:
            - products
        volumes:
            - C:/Users/lstro/source/docker/SageOnline/volumes/products/mssql/data:/var/opt/mssql/data
            - C:/Users/lstro/source/docker/SageOnline/volumes/products/mssql/log:/var/opt/mssql/log
            - C:/Users/lstro/source/docker/SageOnline/volumes/products/mssql/secrets:/var/opt/mssql/secrets

    api-products:
        container_name: api-products
        depends_on:
            - db-products
        image: greytsu/sol_api_products:latest
        ports:
            - 3030:8080
        environment:
            DB_SERVER: mssql-products
            DB_PORT: 1433
            DB_USER: sa
            DB_PASS: Pass@word
            DB_DATABASE: sol_products
            LOG_LEVEL: 1
        networks:
            - products
            - backend
